Rails.application.routes.draw do
  get 'cart_numbers/show'
  get 'cart_numbers/new'
  get 'cart_numbers/edit'
  get 'cart_numbers/index'
  get 'delivery_names/show'
  get 'delivery_names/new'
  get 'delivery_names/edit'
  get 'delivery_names/index'
  get 'order_details/new'
  get 'order_details/show'
  get 'order_details/edit'
  get 'order_details/index'
  get 'chats/new'
  get 'chats/edit'
  get 'chats/show'
  get 'cart_items/index'
  get 'orders/new'
  get 'orders/confirm'
  get 'items/show'
  get 'items/index'
  get 'genres/index'
  get 'deliveries/index'
  get 'deliveries/edit'
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
